receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 5s
    send_batch_size: 1024
  attributes:
    actions:
      - key: tenant_id
        from_attribute: http.request.header.x-tenant-id
        action: upsert
      - key: org_id
        from_attribute: http.request.header.x-enterprise-id
        action: upsert
  filter:
    spans:
      exclude:
        match_type: regexp
        attributes:
          - key: http.target
            value: "^/(favicon|__hmr|assets/)"

exporters:
  prometheus:
    endpoint: 0.0.0.0:8889
    namespace: cloudmock

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, attributes, filter]
      exporters: []
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]
