// JSON syntax highlighting for the cloudmock dashboard.
// Content is generated from our own API responses (trusted, internal dev tool).

export function syntaxHighlight(jsonInput: any): string {
  if (!jsonInput) return '';
  let jsonStr: string;
  try {
    if (typeof jsonInput === 'object') {
      jsonStr = JSON.stringify(jsonInput, null, 2);
    } else {
      jsonStr = JSON.stringify(JSON.parse(jsonInput), null, 2);
    }
  } catch {
    return String(jsonInput);
  }
  return jsonStr.replace(
    /("(\\u[\da-fA-F]{4}|\\[^u]|[^\\"])*"(\s*:)?|\b(true|false|null)\b|-?\d+(?:\.\d*)?(?:[eE][+-]?\d+)?)/g,
    (match) => {
      let cls = 'json-number';
      if (/^"/.test(match)) {
        cls = /:$/.test(match) ? 'json-key' : 'json-string';
      } else if (/true|false/.test(match)) {
        cls = 'json-boolean';
      } else if (/null/.test(match)) {
        cls = 'json-null';
      }
      return `<span class="${cls}">${match}</span>`;
    }
  );
}

interface JsonViewProps {
  data: any;
}

export function JsonView({ data }: JsonViewProps) {
  const highlighted = syntaxHighlight(data || '(empty)');
  // Safe: content is generated by syntaxHighlight from trusted JSON data
  return <div class="json-view" dangerouslySetInnerHTML={{ __html: highlighted }} />;
}
