apiVersion: v2
name: cloudmock
description: A Helm chart for deploying cloudmock in Kubernetes for use with Crossplane
type: application
version: 0.1.0
appVersion: "0.1.0"
home: https://github.com/neureaux/cloudmock
sources:
  - https://github.com/neureaux/cloudmock
maintainers:
  - name: neureaux
    url: https://github.com/neureaux
keywords:
  - cloudmock
  - aws
  - mock
  - crossplane
  - testing
