package main

// terraformEndpoints maps Terraform AWS provider endpoint names to a description.
// These are used to generate the _cloudmock_override.tf file.
var terraformEndpoints = []string{
	"accessanalyzer", "account", "acm", "acmpca", "amplify", "apigateway",
	"apigatewayv2", "appautoscaling", "appconfig", "appflow", "appintegrations",
	"applicationinsights", "appmesh", "apprunner", "appstream", "appsync",
	"athena", "auditmanager", "autoscaling", "autoscalingplans", "backup",
	"batch", "bedrock", "budgets", "ce", "chatbot", "chime", "chimesdkmediapipelines",
	"chimesdkvoice", "cleanrooms", "cloud9", "cloudcontrol", "cloudformation",
	"cloudfront", "cloudhsmv2", "cloudsearch", "cloudtrail", "cloudwatch",
	"cloudwatchevents", "cloudwatchlogs", "codeartifact", "codebuild",
	"codecatalyst", "codecommit", "codedeploy", "codeguruprofiler",
	"codegurureviewer", "codepipeline", "codestarconnections",
	"codestarnotifications", "cognitoidentity", "cognitoidp", "comprehend",
	"computeoptimizer", "configservice", "connect", "connectcases",
	"controltower", "costoptimizationhub", "cur", "customerprofiles",
	"databasemigrationservice", "databrew", "dataexchange", "datapipeline",
	"datasync", "dax", "deploy", "detective", "devicefarm", "directconnect",
	"dlm", "dms", "docdb", "docdbelastic", "drs", "ds", "dynamodb",
	"ec2", "ecr", "ecrpublic", "ecs", "efs", "eks", "elasticache",
	"elasticbeanstalk", "elasticsearch", "elastictranscoder", "elb", "elbv2",
	"emr", "emrcontainers", "emrserverless", "es", "eventbridge", "evidently",
	"firehose", "fis", "fms", "fsx", "gamelift", "glacier", "globalaccelerator",
	"glue", "grafana", "greengrass", "guardduty", "healthlake", "iam",
	"identitystore", "imagebuilder", "inspector", "inspector2", "internetmonitor",
	"iot", "iotanalytics", "iotevents", "ivs", "ivschat", "kafka",
	"kafkaconnect", "kendra", "keyspaces", "kinesis", "kinesisanalytics",
	"kinesisanalyticsv2", "kinesisvideo", "kms", "lakeformation", "lambda",
	"launchwizard", "lex", "lexv2models", "licensemanager", "lightsail",
	"location", "logs", "lookoutmetrics", "m2", "macie2", "mediaconnect",
	"mediaconvert", "medialive", "mediapackage", "mediapackagev2", "mediastore",
	"memorydb", "mq", "msk", "mwaa", "neptune", "networkfirewall",
	"networkmanager", "oam", "opensearch", "opensearchserverless", "opsworks",
	"organizations", "osis", "outposts", "pcaconnectorad", "pinpoint",
	"pipes", "polly", "pricing", "prometheus", "qbusiness", "qldb",
	"quicksight", "ram", "rbin", "rds", "redshift", "redshiftdata",
	"redshiftserverless", "rekognition", "resiliencehub", "resourceexplorer2",
	"resourcegroups", "resourcegroupstaggingapi", "rolesanywhere", "route53",
	"route53domains", "route53profiles", "route53recoverycontrolconfig",
	"route53recoveryreadiness", "route53resolver", "rum", "s3", "s3control",
	"s3outposts", "sagemaker", "scheduler", "schemas", "secretsmanager",
	"securityhub", "securitylake", "serverlessrepo", "servicecatalog",
	"servicediscovery", "servicequotas", "ses", "sesv2", "sfn", "shield",
	"signer", "simpledb", "sns", "sqs", "ssm", "ssmcontacts", "ssmincidents",
	"ssmsap", "ssoadmin", "stepfunctions", "storagegateway", "sts", "support",
	"swf", "synthetics", "timestreaminfluxdb", "timestreamwrite", "transcribe",
	"transfer", "verifiedaccess", "verifiedpermissions", "vpclattice", "waf",
	"wafregional", "wafv2", "wellarchitected", "worklink", "workspaces",
	"workspacesweb", "xray",
}
