package main

import (
	"bufio"
	"flag"
	"fmt"
	"os"
	"os/signal"
	"path/filepath"
	"strings"
	"syscall"
	"time"

	"github.com/neureaux/cloudmock/tools/common"
)

func main() {
	endpoint := flag.String("endpoint", "", "cloudmock endpoint URL")
	realAWS := flag.Bool("real-aws", false, "use real AWS (bypass cloudmock)")
	yes := flag.Bool("yes", false, "skip confirmation prompts")
	flag.Parse()

	args := flag.Args()

	if *realAWS {
		if !*yes {
			if !confirm("You are about to run against REAL AWS. Continue?") {
				fmt.Fprintln(os.Stderr, "Aborted.")
				os.Exit(1)
			}
		}
		if err := common.ExecToolPassthrough("terraform", args); err != nil {
			fmt.Fprintf(os.Stderr, "error: %v\n", err)
			os.Exit(1)
		}
		return
	}

	ep := *endpoint
	if ep == "" {
		ep = common.DetectEndpoint()
	}

	if err := common.WaitForHealth(ep, 30*time.Second); err != nil {
		fmt.Fprintf(os.Stderr, "error: %v\n", err)
		os.Exit(1)
	}

	// Generate override file
	overridePath := filepath.Join(".", "_cloudmock_override.tf")
	if err := writeOverrideFile(overridePath, ep); err != nil {
		fmt.Fprintf(os.Stderr, "cloudmock-terraform: %v\n", err)
		os.Exit(1)
	}

	// Clean up on exit
	cleanup := func() { os.Remove(overridePath) }
	defer cleanup()
	c := make(chan os.Signal, 1)
	signal.Notify(c, os.Interrupt, syscall.SIGTERM)
	go func() { <-c; cleanup(); os.Exit(0) }()

	if err := common.ExecTool("terraform", args, ep); err != nil {
		fmt.Fprintf(os.Stderr, "error: %v\n", err)
		os.Exit(1)
	}
}

func writeOverrideFile(path, endpoint string) error {
	var b strings.Builder
	b.WriteString("# Auto-generated by cloudmock-terraform. Do not edit.\n")
	b.WriteString("# Add _cloudmock_override.tf to .gitignore.\n\n")
	b.WriteString("provider \"aws\" {\n")
	b.WriteString("  access_key                  = \"test\"\n")
	b.WriteString("  secret_key                  = \"test\"\n")
	b.WriteString("  region                      = \"us-east-1\"\n")
	b.WriteString("  skip_credentials_validation = true\n")
	b.WriteString("  skip_metadata_api_check     = true\n")
	b.WriteString("  skip_requesting_account_id  = true\n\n")
	b.WriteString("  endpoints {\n")
	for _, ep := range terraformEndpoints {
		fmt.Fprintf(&b, "    %-40s = %q\n", ep, endpoint)
	}
	b.WriteString("  }\n")
	b.WriteString("}\n")
	return os.WriteFile(path, []byte(b.String()), 0644)
}

func confirm(prompt string) bool {
	fmt.Fprintf(os.Stderr, "%s [y/N] ", prompt)
	scanner := bufio.NewScanner(os.Stdin)
	if scanner.Scan() {
		resp := strings.TrimSpace(strings.ToLower(scanner.Text()))
		return resp == "y" || resp == "yes"
	}
	return false
}
