package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestWriteOverrideFile(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "_cloudmock_override.tf")

	err := writeOverrideFile(path, "http://localhost:4566")
	if err != nil {
		t.Fatalf("writeOverrideFile: %v", err)
	}

	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read: %v", err)
	}

	content := string(data)

	// Verify provider block
	if !strings.Contains(content, `provider "aws"`) {
		t.Error("missing provider block")
	}
	if !strings.Contains(content, "skip_credentials_validation") {
		t.Error("missing skip_credentials_validation")
	}
	if !strings.Contains(content, "skip_metadata_api_check") {
		t.Error("missing skip_metadata_api_check")
	}
	if !strings.Contains(content, `= "http://localhost:4566"`) {
		t.Error("missing endpoint URL")
	}

	// Verify key endpoints present
	for _, ep := range []string{"s3", "dynamodb", "sqs", "lambda", "iam", "ecs", "eks", "rds"} {
		if !strings.Contains(content, ep) {
			t.Errorf("missing endpoint: %s", ep)
		}
	}
}

func TestWriteOverrideFile_CustomEndpoint(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "override.tf")

	err := writeOverrideFile(path, "http://custom:9999")
	if err != nil {
		t.Fatal(err)
	}

	data, _ := os.ReadFile(path)
	if !strings.Contains(string(data), "http://custom:9999") {
		t.Error("custom endpoint not in output")
	}
}

func TestWriteOverrideFile_CreatesFile(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "nested", "subdir", "override.tf")

	// Writing to a non-existent subdirectory should fail (os.WriteFile behaviour).
	// This test verifies we get an error rather than a silent failure.
	err := writeOverrideFile(path, "http://localhost:4566")
	if err == nil {
		t.Error("expected error writing to non-existent subdirectory, got nil")
	}
}

func TestWriteOverrideFile_ContentStructure(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "override.tf")

	err := writeOverrideFile(path, "http://localhost:4566")
	if err != nil {
		t.Fatalf("writeOverrideFile: %v", err)
	}

	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read: %v", err)
	}
	content := string(data)

	// Verify static credential fields are present
	if !strings.Contains(content, `access_key`) {
		t.Error("missing access_key field")
	}
	if !strings.Contains(content, `secret_key`) {
		t.Error("missing secret_key field")
	}
	if !strings.Contains(content, `region`) {
		t.Error("missing region field")
	}

	// Verify endpoints block is present
	if !strings.Contains(content, "endpoints {") {
		t.Error("missing endpoints block")
	}

	// Verify auto-generation header comment
	if !strings.Contains(content, "Auto-generated by cloudmock-terraform") {
		t.Error("missing auto-generation comment")
	}
}

func TestEndpointsList(t *testing.T) {
	if len(terraformEndpoints) < 50 {
		t.Errorf("expected 50+ endpoints, got %d", len(terraformEndpoints))
	}

	// Check critical endpoints exist
	required := []string{
		"s3", "dynamodb", "sqs", "sns", "lambda", "iam", "ec2",
		"ecs", "eks", "rds", "route53", "cloudformation", "kms", "sts",
	}
	endpointSet := make(map[string]bool)
	for _, ep := range terraformEndpoints {
		endpointSet[ep] = true
	}
	for _, req := range required {
		if !endpointSet[req] {
			t.Errorf("missing required endpoint: %s", req)
		}
	}
}

func TestEndpointsList_NoDuplicates(t *testing.T) {
	seen := make(map[string]int)
	for i, ep := range terraformEndpoints {
		if prev, ok := seen[ep]; ok {
			t.Errorf("duplicate endpoint %q at index %d (first seen at %d)", ep, i, prev)
		}
		seen[ep] = i
	}
}

func TestEndpointsList_NoEmptyStrings(t *testing.T) {
	for i, ep := range terraformEndpoints {
		if strings.TrimSpace(ep) == "" {
			t.Errorf("empty endpoint string at index %d", i)
		}
	}
}
