services:
  cloudmock:
    image: ghcr.io/viridian-inc/cloudmock:latest
    ports:
      - "4566:4566"
      - "4500:4500"
    environment:
      CLOUDMOCK_PROFILE: minimal
      CLOUDMOCK_IAM_MODE: none
