name: CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - run: go build $(go list ./... | grep -v create-cloudmock-app/templates)
      - run: go vet $(go list ./... | grep -v create-cloudmock-app/templates)
      - run: go test $(go list ./... | grep -v postgres | grep -v create-cloudmock-app/templates) -timeout 120s
